image: beagle/sphinx-build-env:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: bbdocs
  paths:
  - public

pages:
  script:
  - apk add fonts-dejavu
  - "./gitlab-build.sh"
  artifacts:
    paths:
    - public
