image: beagle/sphinx-build-env:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy

cache:
  key: bbdocs
  paths:
    - public

pages:
  stage: deploy
  script:
    - ./gitlab-build.sh
  artifacts:
    paths:
      - public
