image: beagle/sphinx-build-env:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: bbdocs
  paths:
  - public

pages:
  tags:
    - aarch64
  script:
  - apk add ttf-dejavu ttf-freefont
  - "./gitlab-build.sh"
  artifacts:
    paths:
    - public
