image: beagle/sphinx-build-env:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  - ./gitlab-build.sh
  - export
  artifacts:
    paths:
    - public
  variables:
    CI_DEBUG_TRACE: "true"
