image: beagle/sphinx-build-env:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: bbdocs
  paths:
  - public

pages:
  script:
  - "./gitlab-build.sh"
  artifacts:
    paths:
    - public
  except:
    - tags

docs:
  tags:
  - docs
  script:
  - "./gitlab-build.sh"
  artifacts:
    paths:
    - public
  only:
    - tags
  except:
    - branches
