name: "Sphinx: Render docs"

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: beagle/sphinx-build-env:latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        target: [html, pdf]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build docs (${{ matrix.target }})
      run: |
        source ./venv-build-env.sh
        if [ -e projects/librobotcontrol/docs ]; then
          make librobotcontrol
        fi
        if [ "${{ matrix.target }}" == "html" ]; then
          make html
        elif [ "${{ matrix.target }}" == "pdf" ]; then
          make latexpdf
        else
          echo "Unknown target: ${{ matrix.target }}"
          exit 1
        fi
    - name: Upload ${{ matrix.target }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs-${{ matrix.target }}
        path: ${{ matrix.target == 'html' && '_build/html/' || '_build/latex/*.pdf' }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: always() && (github.ref_type == 'branch' || github.ref_type == 'tag')

    container:
      image: beagle/sphinx-build-env:latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Download HTML docs
      uses: actions/download-artifact@v4
      with:
        name: docs-html
        path: public/html

    - name: Download PDF docs
      uses: actions/download-artifact@v4
      with:
        name: docs-pdf
        path: public/pdf

    - name: Combine artifacts
      run: |
        mv public/html/* public/ || true
        mv public/pdf/*.pdf public/ || true
        rm -rf public/html public/pdf || true

    - name: List published files
      run: ls -lR public

    - name: Decide where to publish
      run: |
        echo "GitHub ref type: ${{ github.ref_type }}"
        if [ "${{ github.ref_type }}" == "branch" ]; then
          echo "Publishing to GitHub Pages..."
        elif [ "${{ github.ref_type }}" == "tag" ]; then
          echo "Publishing to production server via rsync (TODO)..."
          # rsync -avz _build/html/ user@server:/path/
        fi

    - name: Upload to Pages artifact
      if: github.ref_type == 'branch'
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

    - name: Deploy to GitHub Pages
      if: github.ref_type == 'branch'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public

    - name: Cleanup
      run: |
        source ./venv-build-env.sh
        make clean
        rm -rf public/*
