name: "Sphinx: Render docs"

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: beagle/sphinx-build-env:latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        target: [html, pdf]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          .venv
          .cache
        key: sphinx-build-env-docs-003

    - name: Setup build environment
      run: source ./venv-build-env.sh

    - name: Build docs (${{ matrix.target }})
      run: ./gitlab-build.sh ${{ matrix.target }}

    - name: Upload ${{ matrix.target }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}-docs
        path: public/${{ matrix.target }}

  publish:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Download HTML docs
      uses: actions/download-artifact@v4
      with:
        name: html-docs
        path: public/html

    - name: Download PDF docs
      uses: actions/download-artifact@v4
      with:
        name: pdf-docs
        path: public/pdf

    - name: Combine docs for publishing
      run: |
        mkdir -p public
        mv public/html/* public/
        mv public/pdf/*.pdf public/

    - name: Upload published site
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
